import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PetMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider
        appearance={{
            layout:{
                logoImageUrl:"/img/logo.svg",
            },
            variables:{
            
                colorText:'#010101',
                colorPrimary:'#99E550',
                colorBackground:'#fff',
                colorInputBackground:'#fff',
                colorInputText:'#010101',
                colorTextOnPrimaryBackground:'#010101',
                colorTextSecondary:"#010101"
              }
        }}
      > 
      <html lang="es">
        <head>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,1,0" />
        </head>
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
